/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat109.oblig2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {
    
    }
}
